# Tell Travis to use new container-based infrastructure
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=nightly
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
  fast_finish: true
  allow_failures:
    - php: 7.2

branches:
    only:
        - master

before_script:
    # Setup WordPress
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
    - export WP_CORE_DIR=/tmp/wordpress/src/
    - export WP_DEVELOP_DIR=/tmp/wordpress
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php

script:
    - phpunit